# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b4fcdedf662e8bed30be868f7bcbefbf65dc3995cf917e6506328ea2e2ad80677df2168068252a3f236d81d2f6ba7f39f7b9b60bdfbb40ac81a1aff867f1c4d

test:
  secret_key_base: d7eef9b292d6218b479802482290f3268a226dd843ea959e66924d887a2ea8ffeba887ea9ae040dda89ef31ee964dae1a389a9eff2dcb9d5e9e98042b778760b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
